package com.talkingkotlin.util

/**
 * Constants used in the whole app
 * @author Alexander Gherschon
 */

const val NOTIFICATION_ID = 1

const val ITEM_ACTION = "ITEM_ACTION"

const val ACTION_PLAY = "ACTION_PLAY"
const val ACTION_PAUSE = "ACTION_PAUSE"
const val ACTION_RESUME = "ACTION_RESUME"
const val ACTION_STOP = "ACTION_STOP"
const val ACTION_UPDATE_PLAYBACK_SPEED = "ACTION_UPDATE_PLAYBACK_SPEED"
const val ACTION_STATUS = "ACTION_STATUS"

const val BROADCAST_STATE_ACTION = "BROADCAST_STATE_ACTION"

const val BROADCAST_PLAYING_STATS_ACTION = "BROADCAST_PLAYING_STATS_ACTION"
const val EXTRA_STATE = "EXTRA_STATE"
const val EXTRA_DURATION = "EXTRA_DURATION"
const val EXTRA_POSITION = "EXTRA_POSITION"

const val SERVER_DATE_FORMAT = "EEE, d MMM yyyy HH:mm:ss Z"
const val PRESENTED_DATE_FORMAT = "MMMM dd, yyyy"
const val DURATION_TIME_FORMAT = "HH:mm:ss"

const val PLAYBACK_SPEED = "PLAYBACK_SPEED"
const val RATIO_PLAYBACK_SPEED_TO_PROGRESS = 0.25f

const val EXTRA_CARRY_ON = "EXTRA_CARRY_ON"
